---
title: German Credit Data Dictionary
format:
  html:
    embed-resources: true
---

## German Credit Data Set

The data sets defined below describe the characteristics of German credit applicants. These data sets are derived from the [German Credit Data Set](https://archive.ics.uci.edu/dataset/144/statlog+german+credit+data) provided by the UCI Machine Learning Repository.

### Variables: `credit_personal.csv`

`applicant_id` : Applicant identification number

`credit_amount` : Credit amount in Deutsche Mark (DEM)

`age` : Age in years

`personal_status` : Marriage status and sex

`job` : Type of job

`employment` : Years since the present employment started

`savings_status` : Amount in DEM in savings account/bonds 

`housing` : Housing status

`residence_since`: Present residence since

`property_magnitude` : Property type

`num_dependents` : Number of dependents

`own_telephone` : If an applicant owns a telephone

`foreign_worker` : If an applicant is a foreign worker


### Variables: `credit_financial.csv`

`applicant_id` : Applicant identification number

`checking status` : Status of existing checking account

`duration` : Duration of credit in month

`credit_history` : Credit history

`purpose` : Purpose for credit

`installment_commitment` : Installment rate in percentage of disposable income

`other_parties` : Other debtors / guarantors

`other_payment_plans` : Other installment plans

`existing_credits` : Number of existing credits at this bank

`class` : Classification of good (1) or bad (2) credit risk


